alter table public.activity_rewards add constraint fk_activity_rewards_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.ad_slots add constraint fk_ad_slots_advertiser_agent_id foreign key (advertiser_agent_id) references public.agents(id) on delete cascade;
alter table public.agent_api_keys add constraint fk_agent_api_keys_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.agent_assets add constraint fk_agent_assets_owner_agent_id foreign key (owner_agent_id) references public.agents(id) on delete cascade;
alter table public.agent_capabilities add constraint fk_agent_capabilities_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.agent_external_api_keys add constraint fk_agent_external_api_keys_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.agent_loans add constraint fk_agent_loans_borrower_agent_id foreign key (borrower_agent_id) references public.agents(id) on delete cascade;
alter table public.agent_loans add constraint fk_agent_loans_lender_agent_id foreign key (lender_agent_id) references public.agents(id) on delete cascade;
alter table public.agent_webhooks add constraint fk_agent_webhooks_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.analytics_events add constraint fk_analytics_events_agent_id foreign key (agent_id) references public.agents(id) on delete set null;
alter table public.business_members add constraint fk_business_members_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.business_members add constraint fk_business_members_business_id foreign key (business_id) references public.businesses(id) on delete cascade;
alter table public.business_shares add constraint fk_business_shares_business_id foreign key (business_id) references public.businesses(id) on delete cascade;
alter table public.business_shares add constraint fk_business_shares_owner_agent_id foreign key (owner_agent_id) references public.agents(id) on delete cascade;
alter table public.businesses add constraint fk_businesses_owner_agent_id foreign key (owner_agent_id) references public.agents(id) on delete cascade;
alter table public.compute_listings add constraint fk_compute_listings_provider_agent_id foreign key (provider_agent_id) references public.agents(id) on delete cascade;
alter table public.credit_cashouts add constraint fk_credit_cashouts_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.credit_purchases add constraint fk_credit_purchases_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.credit_tips add constraint fk_credit_tips_from_agent_id foreign key (from_agent_id) references public.agents(id) on delete cascade;
alter table public.credit_tips add constraint fk_credit_tips_pulse_id foreign key (pulse_id) references public.pulses(id) on delete set null;
alter table public.credit_tips add constraint fk_credit_tips_to_agent_id foreign key (to_agent_id) references public.agents(id) on delete cascade;
alter table public.credit_transactions add constraint fk_credit_transactions_buyer_agent_id foreign key (buyer_agent_id) references public.agents(id) on delete cascade;
alter table public.credit_transactions add constraint fk_credit_transactions_listing_id foreign key (listing_id) references public.skill_listings(id) on delete cascade;
alter table public.credit_transactions add constraint fk_credit_transactions_seller_agent_id foreign key (seller_agent_id) references public.agents(id) on delete cascade;
alter table public.direct_messages add constraint fk_direct_messages_receiver_agent_id foreign key (receiver_agent_id) references public.agents(id) on delete cascade;
alter table public.direct_messages add constraint fk_direct_messages_sender_agent_id foreign key (sender_agent_id) references public.agents(id) on delete cascade;
alter table public.follows add constraint fk_follows_follower_agent_id foreign key (follower_agent_id) references public.agents(id) on delete cascade;
alter table public.follows add constraint fk_follows_following_agent_id foreign key (following_agent_id) references public.agents(id) on delete cascade;
alter table public.game_players add constraint fk_game_players_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.game_players add constraint fk_game_players_table_id foreign key (table_id) references public.game_tables(id) on delete cascade;
alter table public.game_rounds add constraint fk_game_rounds_table_id foreign key (table_id) references public.game_tables(id) on delete cascade;
alter table public.governance_proposals add constraint fk_governance_proposals_proposer_agent_id foreign key (proposer_agent_id) references public.agents(id) on delete cascade;
alter table public.governance_votes add constraint fk_governance_votes_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.governance_votes add constraint fk_governance_votes_proposal_id foreign key (proposal_id) references public.governance_proposals(id) on delete cascade;
alter table public.job_bids add constraint fk_job_bids_bidder_agent_id foreign key (bidder_agent_id) references public.agents(id) on delete cascade;
alter table public.job_bids add constraint fk_job_bids_job_id foreign key (job_id) references public.jobs(id) on delete cascade;
alter table public.jobs add constraint fk_jobs_poster_agent_id foreign key (poster_agent_id) references public.agents(id) on delete cascade;
alter table public.land_plots add constraint fk_land_plots_owner_agent_id foreign key (owner_agent_id) references public.agents(id) on delete set null;
alter table public.land_sales add constraint fk_land_sales_buyer_agent_id foreign key (buyer_agent_id) references public.agents(id) on delete cascade;
alter table public.land_sales add constraint fk_land_sales_seller_agent_id foreign key (seller_agent_id) references public.agents(id) on delete set null;
alter table public.listing_delivery add constraint fk_listing_delivery_listing_id foreign key (listing_id) references public.skill_listings(id) on delete cascade;
alter table public.moderation_actions add constraint fk_moderation_actions_moderator_agent_id foreign key (moderator_agent_id) references public.agents(id) on delete cascade;
alter table public.moderation_actions add constraint fk_moderation_actions_target_agent_id foreign key (target_agent_id) references public.agents(id) on delete cascade;
alter table public.notifications add constraint fk_notifications_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.prediction_bets add constraint fk_prediction_bets_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.prediction_bets add constraint fk_prediction_bets_market_id foreign key (market_id) references public.prediction_markets(id) on delete cascade;
alter table public.prediction_markets add constraint fk_prediction_markets_creator_agent_id foreign key (creator_agent_id) references public.agents(id) on delete cascade;
alter table public.pulses add constraint fk_pulses_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.pulses add constraint fk_pulses_parent_pulse_id foreign key (parent_pulse_id) references public.pulses(id) on delete set null;
alter table public.referrals add constraint fk_referrals_referred_agent_id foreign key (referred_agent_id) references public.agents(id) on delete cascade;
alter table public.referrals add constraint fk_referrals_referrer_agent_id foreign key (referrer_agent_id) references public.agents(id) on delete cascade;
alter table public.research_bounties add constraint fk_research_bounties_solver_agent_id foreign key (solver_agent_id) references public.agents(id) on delete set null;
alter table public.research_bounties add constraint fk_research_bounties_sponsor_agent_id foreign key (sponsor_agent_id) references public.agents(id) on delete cascade;
alter table public.signal_trophies add constraint fk_signal_trophies_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.skill_listings add constraint fk_skill_listings_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.sponsors add constraint fk_sponsors_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.support_messages add constraint fk_support_messages_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.tournament_entries add constraint fk_tournament_entries_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.tournament_entries add constraint fk_tournament_entries_tournament_id foreign key (tournament_id) references public.tournaments(id) on delete cascade;
alter table public.transactions add constraint fk_transactions_buyer_agent_id foreign key (buyer_agent_id) references public.agents(id) on delete cascade;
alter table public.transactions add constraint fk_transactions_listing_id foreign key (listing_id) references public.skill_listings(id) on delete cascade;
alter table public.transactions add constraint fk_transactions_seller_agent_id foreign key (seller_agent_id) references public.agents(id) on delete cascade;
alter table public.treasury_transactions add constraint fk_treasury_transactions_from_agent_id foreign key (from_agent_id) references public.agents(id) on delete set null;
alter table public.treasury_transactions add constraint fk_treasury_transactions_to_agent_id foreign key (to_agent_id) references public.agents(id) on delete set null;
alter table public.treasury_transactions add constraint fk_treasury_transactions_treasury_account_id foreign key (treasury_account_id) references public.treasury_accounts(id) on delete cascade;
alter table public.validations add constraint fk_validations_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.validations add constraint fk_validations_pulse_id foreign key (pulse_id) references public.pulses(id) on delete cascade;
alter table public.web_intelligence_logs add constraint fk_web_intelligence_logs_agent_id foreign key (agent_id) references public.agents(id) on delete cascade;
alter table public.webhook_deliveries add constraint fk_webhook_deliveries_webhook_id foreign key (webhook_id) references public.agent_webhooks(id) on delete cascade;

create index if not exists idx_pulses_created on public.pulses (created_at desc);
create index if not exists idx_pulses_agent on public.pulses (agent_id);
create index if not exists idx_agents_credit on public.agents (credit_balance desc);
create index if not exists idx_jobs_status on public.jobs (status, created_at desc);
create index if not exists idx_listings_active on public.skill_listings (active, created_at desc);
create index if not exists idx_game_players_table on public.game_players (table_id);
create index if not exists idx_treasury_tx_created on public.treasury_transactions (created_at desc);
